# action.yml
name: 'Sync Folder to Repository'
description: 'Synchronize a folder from one repository to another'
inputs:
  primary_repo_folder:
    description: 'Folder in primary repository with docs to sync'
    required: true
  bidi_sync_repo:
    description: 'Sync repository to push documentation'
    required: true
  bidi_sync_folder:
    description: 'Destination folder in sync repository (leave empty for root)'
    required: false
    default: ''
  bidi_sync_branch:
    description: 'Target branch in sync repository'
    required: true
  access_token:
    description: 'GitHub token with repository access'
    required: true
  git_user_name:
    description: 'Git user name for commits'
    required: false
    default: 'GitHub Actions Bot'
  git_user_email:
    description: 'Git user email for commits'
    required: false
    default: 'noreply@github.com'

runs:
  using: 'composite'
  steps:
    - name: Checkout primary repository
      uses: actions/checkout@v4
      with:
        path: primary-repo
        ref: ${{ github.ref }}

    - name: Checkout BiDi Sync repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.bidi_sync_repo }}
        path: bidi-sync-repo
        token: ${{ inputs.access_token }}
        ref: ${{ inputs.bidi_sync_branch }}
        
    - name: Sync Documentation
      shell: bash
      env:
        PRIMARY_REPO_FOLDER: ${{ inputs.primary_repo_folder }}
        BIDI_SYNC_FOLDER: ${{ inputs.bidi_sync_folder }}
        BIDI_SYNC_BRANCH: ${{ inputs.bidi_sync_branch }}
        GIT_USER_NAME: ${{ inputs.git_user_name }}
        GIT_USER_EMAIL: ${{ inputs.git_user_email }}
      run: ${{ github.action_path }}/sync-docs.sh